export { CartPage } from './cart';
export { HomePage } from './home';
export { BasketPage } from './basket';
export { ProfilePage } from './profile';
export { ProductsPage } from './products';
export { FavouritesPage } from './favourites';
export { CategoriesPage } from './categories';
export { OrdersPage } from './profile/orders';
export { UserLimitsPage } from './profile/limits';
export { SingleProductPage } from './single-product';
export { UserAccountPage } from './profile/account';
export { FormalizationPage } from './formalization';
export {CategoriesProductsPage} from './categories/categories-products';
